#Numpy Array Operations:  

1. Create a 1D NumPy Array:  
Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:  
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]  

In [ ]:
import numpy as np
Week_1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
temperatures_w1 = np.array(Week_1)
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2. Inspection and Properties:  
● Inspect the shape, data type, and the number of elements in the array. Inspect
the shape of the temperatures_w1 array.  

In [ ]:
print(f'Shape of the aray: {temperatures_w1.shape}')
print(f'Datatype of the array: {temperatures_w1.dtype}')
print(f'Number of elements in the array: {temperatures_w1.size}')


Shape of the aray: (7,)
Datatype of the array: float64
Number of elements in the array: 7


3. Array Operations:  
● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
Fahrenheit = (Celsius * 9/5) + 32  
● Find the maximum, minimum, and mean temperatures for the week.

In [ ]:
fahrenheit = (temperatures_w1 * 9/5) + 32
print(fahrenheit)

print(f'\n maximum temperatures for the week: {np.max(fahrenheit)}')
print(f'\n minimum temperatures for the week: {np.min(fahrenheit)}')
print(f'\n mean temperatures for the week: {np.mean(fahrenheit)}')

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

 maximum temperatures for the week: 78.98

 minimum temperatures for the week: 69.44

 mean temperatures for the week: 74.37714285714286


4. Array Slicing and Indexing:  
● Extract the temperatures for the first three days of the week.  
● Extract the temperatures for the weekend (last two days).  
● Extract the temperatures for the middle three days of the week.

In [ ]:
print(f'temperatures for the first three days of the week: {fahrenheit[:3]}')
print(f'temperatures for the weekend(last two days): {fahrenheit[-2:]}')
print(f'temperatures for the middle three days of the week: {fahrenheit[2:5]}')

temperatures for the first three days of the week: [72.5  77.54 69.44]
temperatures for the weekend(last two days): [76.64 71.42]
temperatures for the middle three days of the week: [69.44 74.12 78.98]


5. Create a 2D Array:  
Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:  
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)  
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)  

In [ ]:
week1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
week2 = [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]

temperatures = np.array([week1,week2])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6. Inspect and Slice the 2D Array:  
● Inspect and print the shape, data type, and total number of elements in the
temperatures array.  
● Extract the temperatures for each week and the weekends (last two days) for
both weeks.

In [ ]:
print(f'Shape of the array: {temperatures.shape}')
print(f'Datatype of the array: {temperatures.dtype}')
print(f'Number of elements in the array: {temperatures.size}')
print(f'Week1: {temperatures[0]}')
print(f'Week2: {temperatures[1]}')
print(f'Temperatures of Last two days for both week: {temperatures[0:,5:]}')

Shape of the array: (2, 7)
Datatype of the array: float64
Number of elements in the array: 14
Week1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Temperatures of Last two days for both week: [[24.8 21.9]
 [22.8 20.1]]


#Pandas Series:

1. Creating Pandas Series:  
● Create a Pandas Series named marks with the following data:  
➢ Marks: 95, 92, 89, 85, 80  
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [ ]:
import pandas as pd
marks = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. Indexing and Slicing:  
●  Use the integer index position to access the mark of the 1st rank student.  
●  Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
labels.  
● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.  
● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
greater than 90.  

In [ ]:
print(f'Mark of the 1st rank student: {marks.iloc[0]}')
print(f'\nMarks of top 3 ranks:\n{marks.loc[['Rank1','Rank2','Rank3']]}')
print(f'\nMark of the 3rd-ranked student: {marks.iloc[2]}')
print(f'\nRanks where the marks are greater than 90:\n{marks[marks > 90]}')

Mark of the 1st rank student: 95

Marks of top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of the 3rd-ranked student: 89

Ranks where the marks are greater than 90:
Rank1    95
Rank2    92
dtype: int64


3. Manipulating Series:  
● Modify the mark of the student with the 1st rank to 100.  
● Remove the entry corresponding to the last rank from the Series.  
● Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
marks['Rank1'] = 100
print(f'The mark of the student with the 1st rank is: \n{marks}')

The mark of the student with the 1st rank is: 
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
marks.drop('Rank5', inplace = True)
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
CGPA = marks / 10
print(f'CGPA of each marks:\n{CGPA}')

CGPA of each marks:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# Pandas DataFrame:  


1. Creating Pandas DataFrame:  
● Create a Pandas DataFrame named transactions with the following data: ➢
TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110  
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'  
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'  
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [ ]:
data = {'TransactionID' : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'ProductCategory' : ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
'Region' : [ 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
'Amount' : [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}
transactions = pd.DataFrame(data)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


2. Data Exploration:  
● Display the transactions DataFrame and its basic information, including head, tail,
shape, column names, and data types.  
● Display only the 'ProductCategory' and 'Amount' columns.  
● Retrieve the last 3 columns of the DataFrame using iloc or loc.  
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.  
● Find the value counts for the 'ProductCategory' column.  
● Find the unique values in the 'Region' column.  
● Group by 'Region' and find the mean amount for each region.

In [ ]:
print(f'Transactions Dataframe: \n {transactions}')

Transactions Dataframe: 
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(f'Transaction Head:\n{transactions.head()}')

Transaction Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [ ]:
print(f'Transaction Tail:\n{transactions.tail()}')

Transaction Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(f'Shape of the Transactions: \n{transactions.shape}')

Shape of the Transactions: 
(10, 4)


In [ ]:
print(f'Column names of the Transactions: \n{transactions.columns}')

Column names of the Transactions: 
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [ ]:
print(f'Datatype of the Transactions: \n{transactions.dtypes}')

Datatype of the Transactions: 
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [ ]:
# Display only the 'ProductCategory' and 'Amount' columns.
print(f'{transactions[['ProductCategory','Amount']]}')

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.
print(f'\n Last 3 columns of the DataFrame:\n{transactions.iloc[0:,1:]} ')


 Last 3 columns of the DataFrame:
  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400 


In [ ]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
#Find the value counts for the 'ProductCategory' column.

print(f'Count of product category: \n\n{transactions['ProductCategory'].value_counts()}')

Count of product category: 

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
# Find the unique values in the 'Region' column.

print(f'Unique values in the Region column: {transactions['Region'].unique()}')


Unique values in the Region column: ['North' 'South' 'East' 'West']


In [ ]:
# Group by 'Region' and find the mean amount for each region.
print(f'Mean amount of each Region:\n\n{transactions.groupby('Region')['Amount'].mean()}')

Mean amount of each Region:

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


3. Manipulating the DataFrame:  
●  Modify the 'Amount' for the transaction with TransactionID 102 to 165.  
● Add a new column 'Discount' by calculating 10% of the 'Amount'.
●  Remove the row with TransactionID 109.  
●  Delete the 'Discount' column from the DataFrame

In [ ]:
# Update Amount for ID 102
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

# Add Discount column
transactions['Discount'] = transactions['Amount'] * 0.10

# Remove TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

# Delete Discount column
transactions = transactions.drop(columns=['Discount'])

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
